version: '2'
services:
  # --------------------------------------------------------------------------
  # HTTP Server
  # --------------------------------------------------------------------------
  nginx:
    image: nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    command: bash -x app/run_nginx.sh
    volumes:
      - ./nginx/logs:/var/log/nginx
      - .:/app
#      - ./certs:/certs
    env_file: .env
    links:
      - django:django
    container_name: nginx


  # --------------------------------------------------------------------------
  # Database
  # --------------------------------------------------------------------------
  mysql:
    image: mysql:5.7
    hostname: mysql
    # volumes:
    #   - ./logs/mysql_log:/var/log/mysql
    env_file: .env
    ports:
      - 3306:3306
    container_name: mysql

  
  # --------------------------------------------------------------------------
  # Message queue
  # --------------------------------------------------------------------------
  rabbit:
    image: rabbitmq:3.5.7
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672" 
      - "15672:15672"
    container_name: rabbit

  flower:
    image: totem/celery-flower-docker
    hostname: flower
    ports:
      - "5555:5555"
#    environment:
#      - AMQP_USERNAME=${AMQP_USERNAME}
#      - AMQP_PASSWORD=${AMQP_PASSWORD}
#      - AMQP_HOST=rabbit
#      - AMQP_PORT=${AMQP_PORT}
#      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
#    volumes:
#      - .:/app
    env_file: .env
    links:
      - rabbit
    container_name: flower


  # --------------------------------------------------------------------------
  # Cache
  # --------------------------------------------------------------------------
  memcached:
    image: memcached
    hostname: memcached
    ports:
      - "11211:11211"
    command: "/usr/local/bin/memcached -u memcache -vv"
    container_name: memcached


  # --------------------------------------------------------------------------
  # Django
  # --------------------------------------------------------------------------
  django:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: django
    command: bash run_django.sh
    volumes:
      - ./logs/django_log:/var/log/
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    links:
      - mysql
      - rabbit
      - memcached
    container_name: django


  # --------------------------------------------------------------------------
  # Celery Workers
  # --------------------------------------------------------------------------
  worker_site:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh run_site.sh
    volumes:
      - .:/app
    env_file: .env
    links:
      - mysql
      - rabbit
    container_name: worker_site
      
  worker_compute:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh run_compute.sh
    volumes:
      - .:/app
    env_file: .env
    links:
      - mysql
      - rabbit
    container_name: worker_compute
