version: '2'
services:
  # --------------------------------------------------------------------------
  # HTTP Server
  # --------------------------------------------------------------------------
  nginx:
#    build: ./nginx/
    image: nginx
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - DJANGO_PORT=${DJANGO_PORT}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
#    command: bash
    command: bash -x app/run_nginx.sh
#    command: bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
#      - .nginx/logs:/var/log/nginx
      - .:/app
    links:
      - django:django
    container_name: nginx


  # --------------------------------------------------------------------------
  # Celery Workers
  # --------------------------------------------------------------------------
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    container_name: mysql

  
  # --------------------------------------------------------------------------
  # Message queue
  # --------------------------------------------------------------------------
  rabbit:
    image: rabbitmq:3.5.7
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672" 
      - "15672:15672"
    container_name: rabbit

  flower:
    image: totem/celery-flower-docker
    hostname: flower
    ports:
      - "5555:5555"
    environment:
      - AMQP_USERNAME=${AMQP_USERNAME}
      - AMQP_PASSWORD=${AMQP_PASSWORD}
      - AMQP_HOST=rabbit
      - AMQP_PORT=${AMQP_PORT}
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
    volumes:
      - .:/app
    links:
      - rabbit
    container_name: flower


  # --------------------------------------------------------------------------
  # Cache
  # --------------------------------------------------------------------------
  memcached:
    image: memcached
    hostname: memcached
    ports:
      - "11211:11211"
    command: "/usr/local/bin/memcached -u memcache -vv"
    container_name: memcached


  # --------------------------------------------------------------------------
  # Django
  # --------------------------------------------------------------------------
  django:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: django
    command: bash run_django.sh
    volumes:
      - .:/app
    env_file: .env 
    ports:
      - "8000:8000"
    links:
      - mysql
      - rabbit
      - memcached
    container_name: django


  # --------------------------------------------------------------------------
  # Celery Workers
  # --------------------------------------------------------------------------
  worker_site:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh run_site.sh
    volumes:
      - .:/app
    links:
      - mysql
      - rabbit
    container_name: worker_site
      
  worker_compute:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh run_compute.sh
    volumes:
      - .:/app
    links:
      - mysql
      - rabbit
    container_name: worker_compute
