version: '2'
services:
  # --------------------------------------------------------------------------
  # HTTP Server
  # --------------------------------------------------------------------------
  nginx:
    image: nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${SSL_PORT}:${SSL_PORT}
    command: bash -x app/docker/run_nginx.sh
    volumes:
      - ${LOG_DIR}/nginx:/var/log/nginx/
      - .:/app
    env_file: .env
    links:
      - django:django
    container_name: nginx


  # --------------------------------------------------------------------------
  # Database
  # --------------------------------------------------------------------------
  mysql:
    image: mysql:5.7
    hostname: mysql
    volumes:
      - ./docker:/app/docker
      - ${LOG_DIR}/mysql:/var/log/
    env_file: .env
    ports:
      - 3306:3306
    container_name: mysql


  # --------------------------------------------------------------------------
  # Message queue
  # --------------------------------------------------------------------------
  rabbit:
    image: rabbitmq:3.5.7
    hostname: rabbit
    command: bash -x app/docker/run_rabbitmq.sh
    env_file: .env
    volumes:
      - ./docker:/app/docker
      - ./certs:/app/certs
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    container_name: rabbit

  flower:
    image: totem/celery-flower-docker
    hostname: flower
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    environment:
      # These aren't set in .env
      - AMQP_USERNAME=${RABBITMQ_DEFAULT_USER}
      - AMQP_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - AMQP_HOST=rabbit
      - AMQP_PORT=${RABBITMQ_PORT}
    volumes:
      - .:/app
    env_file: .env
    links:
      - rabbit
    container_name: flower


  # --------------------------------------------------------------------------
  # Cache
  # --------------------------------------------------------------------------
  memcached:
    image: memcached
    hostname: memcached
    ports:
      - ${MEMCACHED_PORT}:${MEMCACHED_PORT}
    command: "/usr/local/bin/memcached -u memcache -vv"
    container_name: memcached


  # --------------------------------------------------------------------------
  # Django
  # --------------------------------------------------------------------------
  django:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: django
    command: bash docker/run_django.sh
    volumes:
      - ${LOG_DIR}/django:/var/log/django/
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    links:
      - mysql
      - rabbit
      - memcached
    container_name: django


  # --------------------------------------------------------------------------
  # Celery Workers
  # --------------------------------------------------------------------------
  worker_site:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh docker/run_site.sh
    volumes:
      - .:/app
    env_file: .env
    links:
      - mysql
      - rabbit
    container_name: worker_site
      
  worker_compute:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh docker/run_compute.sh
    volumes:
      - .:/app
    env_file: .env
    links:
      - mysql
      - rabbit
    container_name: worker_compute
